version: '2'
services:
    getdockerd-app:
        image: getdockerd
        external_links:
            - getdockerd-postgresql:postgresql
            - getdockerd-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/getdockerd
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    getdockerd-postgresql:
        extends:
            file: postgresql.yml
            service: getdockerd-postgresql
    getdockerd-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: getdockerd-elasticsearch
